# Data structures in pandas

In [1]:
# pandas deals with one data structure i.e, dataframes

# Data Frames

In [2]:
# Dataframes is a two dimensional array with heterogenous data
# Data is aligned in tabular fashion with rows and columns
# Dataframe is a temporary container which is used to store data coming from external source like excel sheets.

# pandas

In [3]:
# pip install pandas

In [4]:
import pandas as pd

# we can create dataframes using list, dictionary and files.

## create an empty data frame

In [5]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

## creating a dataframe using list

In [6]:
l1 = [10,20,30,40,50]
df1 = pd.DataFrame(l1)
df1

    0
0  10
1  20
2  30
3  40
4  50

In [7]:
l1 = [10,20,30,40,50]
df1 = pd.DataFrame(l1,columns=['Numbers'])
df1

   Numbers
0       10
1       20
2       30
3       40
4       50

In [8]:
l1 = [10,20,30,40,50]
df1 = pd.DataFrame(l1,columns = ['Numbers'], index = ['r1', 'r2', 'r3', 'r4', 'r5'])
df1

    Numbers
r1       10
r2       20
r3       30
r4       40
r5       50

## creating a data frame using dictionary

In [9]:
dict1 = {"name" : "ramesh", "age" : 20, "place" : "Bangalore"}

In [10]:
dict1 = {"names" : ["ramesh","suresh","vignesh"],
        "age" : [20,21,22],
        "places": ["bangalore", "mangalore", "cudalore"]}
df2 = pd.DataFrame(dict1)
df2

     names  age     places
0   ramesh   20  bangalore
1   suresh   21  mangalore
2  vignesh   22   cudalore

In [11]:
nested_data = [["ram",20,"bangalore"],
              ["suresh",21,"mangalore"],
              ["veena",22,"cudalore"]]
df3 = pd.DataFrame(nested_data,columns = ["Name","Age","Place"])
df3

     Name  Age      Place
0     ram   20  bangalore
1  suresh   21  mangalore
2   veena   22   cudalore

# create a dataframe using csv file

In [12]:
mobiledataset_df = pd.read_csv('mobiledataset.csv')
mobiledataset_df

      battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0               842          2.2         0      NaN  2549     1            1
1              1021          0.5         1      NaN  2631     0            2
2               563          0.5         1      NaN  2603     0            2
3               615          2.5         0      6.0  2769     0            2
4              1821          1.2         0      2.0  1411     0            1
...             ...          ...       ...      ...   ...   ...          ...
1995            794          0.5         1      6.0   668     0            0
1996           1965          2.6         1      4.0  2032     1            2
1997           1911          0.9         1      8.0  3057     0            3
1998           1512          0.9         0      5.0   869     1            0
1999            510          2.0         1      6.0  3919     1            3

[2000 rows x 7 columns]

In [13]:
# mobiledataset_df = pd.read_csv('C:/Users/ganga/Downloads/mobiledataset.csv')
# mobiledataset_df

In [14]:
mobiledataset_df.shape

(2000, 7)

In [15]:
mobiledataset_df.columns

Index(['battery_power', 'clock_speed', 'dual_sim', 'n_cores', 'ram', 'wifi',
       'price_range'],
      dtype='str')

In [16]:
mobiledataset_df.head()

   battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0            842          2.2         0      NaN  2549     1            1
1           1021          0.5         1      NaN  2631     0            2
2            563          0.5         1      NaN  2603     0            2
3            615          2.5         0      6.0  2769     0            2
4           1821          1.2         0      2.0  1411     0            1

In [17]:
mobiledataset_df.head(20)

    battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0             842          2.2         0      NaN  2549     1            1
1            1021          0.5         1      NaN  2631     0            2
2             563          0.5         1      NaN  2603     0            2
3             615          2.5         0      6.0  2769     0            2
4            1821          1.2         0      2.0  1411     0            1
5            1859          0.5         1      1.0  1067     0            1
6            1821          1.7         0      8.0  3220     1            3
7            1954          0.5         1      4.0   700     1            0
8            1445          0.5         0      7.0  1099     0            0
9             509          0.6         1      5.0   513     0            0
10            769          2.9         1      5.0  3946     0            3
11           1520          2.2         0      8.0  3826     1            3
12           1815          2.8         0      4.0  1482     0            1
13            803          2.1         0      4.0  2680     1            2
14           1866          0.5         0      1.0   373     1            0
15            775          1.0         0      2.0   568     1            0
16            838          0.5         0      8.0  3554     1            3
17            595          0.9         1      3.0  3752     0            3
18           1131          0.5         1      5.0  1835     0            1
19            682          0.5         0      4.0  2337     1            1

In [18]:
pd.set_option('display.max_rows',None)

In [19]:
mobiledataset_df

      battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0               842          2.2         0      NaN  2549     1            1
1              1021          0.5         1      NaN  2631     0            2
2               563          0.5         1      NaN  2603     0            2
3               615          2.5         0      6.0  2769     0            2
4              1821          1.2         0      2.0  1411     0            1
5              1859          0.5         1      1.0  1067     0            1
6              1821          1.7         0      8.0  3220     1            3
7              1954          0.5         1      4.0   700     1            0
8              1445          0.5         0      7.0  1099     0            0
9               509          0.6         1      5.0   513     0            0
10              769          2.9         1      5.0  3946     0            3
11             1520          2.2         0      8.0  3826     1            3
12             1815          2.8         0      4.0  1482     0            1
13              803          2.1         0      4.0  2680     1            2
14             1866          0.5         0      1.0   373     1            0
15              775          1.0         0      2.0   568     1            0
16              838          0.5         0      8.0  3554     1            3
17              595          0.9         1      3.0  3752     0            3
18             1131          0.5         1      5.0  1835     0            1
19              682          0.5         0      4.0  2337     1            1
20              772          1.1         1      7.0  2819     0            3
21             1709          2.1         0      2.0  3283     0            3
22             1949          2.6         1      4.0  1433     1            1
23             1602          2.8         1      3.0  1037     0            0
24              503          1.2         1      3.0  2583     0            1
25              961          1.4         1      8.0  2782     1            2
26              519          1.6         1      4.0  3763     1            3
27              956          0.5         0      7.0  3286     0            3
28             1453          1.6         1      2.0  2373     1            2
29              851          0.5         0      5.0   478     1            0
30             1579          0.5         1      7.0  3532     1            3
31             1568          0.5         0      8.0   508     1            0
32             1319          0.9         0      1.0  2227     1            1
33             1310          2.2         1      4.0  3845     0            3
34              644          2.7         0      8.0  1262     0            0
35              725          1.3         1      8.0  1326     0            1
36              589          2.3         1      4.0  2113     1            1
37             1725          1.6         1      2.0  3429     0            3
38              790          2.0         1      6.0  3169     1            2
39              560          0.5         1      2.0  2150     0            2
40             1347          2.9         0      1.0  2484     1            2
41             1646          2.3         0      2.0  3339     0            3
42             1253          0.5         1      2.0  1878     0            1
43             1656          1.0         0      3.0  1629     0            1
44             1195          2.8         0      2.0   504     0            0
45             1514          2.9         0      3.0  1152     1            1
46             1723          1.1         1      8.0  3587     0            3
47             1054          1.8         1      7.0  2296     1            1
48              578          2.6         1      8.0  1270     1            0
49              596          2.1         1      8.0  3238     0            3
50             1547          3.0         1      3.0  2059     1            2
51             1760          1.4         1      8.0  2053     0            2
52             1654          1.5         1      2.0  3112     0            3
53             1457          1.9         1      3.0  1440     1            1
54             1073          0.5         1      7.0  2908     0            2
55             1936          2.1         1      3.0  2552     0            2
56              823          2.7         1      8.0   905     1            0
57              987          1.3         1      3.0  3963     1            3
58             1757          0.5         0      6.0  2056     0            1
59             1063          1.4         1      5.0  2910     1            2
60             1484          3.0         0      3.0  1457     0            1
61              799          2.3         0      8.0   431     1            0
62             1156          1.2         1      2.0   470     0            0
63             1720          2.0         0      2.0  2148     1            2
64              702          2.6         1      3.0  2955     0            2
65              616          1.9         1      3.0  3366     0            3
66             1358          0.5         0      4.0  3068     0            3
67             1866          1.4         0      3.0  3834     0            3
68             1242          1.1         1      2.0  1050     1            0
69             1166          1.5         1      4.0  3993     0            3
70             1448          0.5         1      7.0  3378     1            3
71             1407          2.4         0      4.0  2192     1            2
72              605          1.0         0      3.0   392     0            0
73             1038          1.2         0      1.0  3709     1            3
74              797          2.9         1      4.0   590     0            0
75              819          0.6         1      6.0  1814     1            1
76             1114          2.8         0      3.0   907     0            0
77             1234          1.6         1      1.0  1449     1            0
78             1199          2.5         1      4.0  3448     1            3
79             1103          1.0         1      6.0  1837     1            1
80             1589          0.6         1      7.0  3464     1            3
81              999          2.9         1      4.0  2593     0            2
82             1510          0.9         1      5.0  3484     1            3
83             1008          0.8         0      3.0  2009     0            1
84             1127          2.9         1      1.0  2048     1            1
85             1412          2.4         0      8.0   837     1            1
86             1496          2.0         1      5.0   854     1            0
87             1083          2.9         1      3.0  3210     0            3
88              668          0.5         1      5.0  2746     1            2
89             1309          1.1         1      4.0  2334     1            2
90             1724          2.0         1      3.0  2822     0            3
91             1977          2.0         1      7.0  1971     0            2
92              885          2.3         1      7.0  1410     1            0
93              879          2.5         0      6.0   349     1            0
94             1322          1.7         1      3.0  1418     0            1
95             1137          1.0         0      3.0  3616     1            3
96             1355          2.3         0      5.0   880     0            0
97             1665          0.5         0      6.0  1601     0            2
98              657          2.5         0      2.0  1412     0            0
99              593          0.5         0      7.0  1692     0            1
100            1883          0.5         0      6.0  2600     0            3
101            1732          1.1         0      8.0  1308     1            1
102             543          0.5         0      5.0  2413     0            1
103            1939          2.8         1      4.0  1047     0            0
104             553          2.4         1      7.0  1204     1            0
105             832          0.7         1      4.0  1799     1            1
106            1661          1.9         1      5.0  2676     1            3
107            1657          2.4         0      5.0  2597     0            3
108            1135          2.0         1      1.0  3029     1            3
109            1775          1.5         0      1.0  2343     1            3
110             783          1.8         1      3.0  2016     0            1
111             617          2.3         0      7.0  2213     0            1
112             867          1.4         1      6.0   790     0            0
113            1310          1.1         1      5.0  3182     0            2
114            1804          0.5         0      7.0  3472     1            3
115            1900          2.3         0      7.0  2871     1            3
116             909          1.4         0      8.0  3187     0            2
117            1084          2.6         0      3.0  1945     0            1
118            1308          1.3         1      1.0   488     0            0
119            1778          0.5         0      3.0  1214     0            1
120            1701          1.6         1      8.0  2598     0            2
121             772          2.4         1      4.0  3242     0            3
122             825          0.5         1      3.0  3534     0            3
123            1379          1.1         0      2.0  3426     1            3
124            1166          2.0         0      5.0  2488     0            2
125            1659          2.8         0      1.0  3255     1            3
126             826          2.4         1      4.0  2863     1            2
127            1564          2.3         0      6.0  1496     1            1
128            1957          0.9         1      3.0  3801     1            3
129            1571          1.4         0      6.0   666     0            0
130            1414          2.0         1      7.0  3799     1            3
131            1790          2.5         1      1.0  1366     1            1
132             645          0.5         0      7.0  2962     1            2
133             668          2.9         1      8.0  2399     1            1
134            1652          1.1         1      4.0  2338     0            2
135            1213          0.5         0      5.0  2700     1            2
136            1272          2.5         1      6.0  2235     0            1
137             866          0.5         1      8.0  3825     1            3
138             536          2.4         1      7.0   284     0            0
139             523          2.6         1      8.0  1427     0            0
140            1753          0.5         1      1.0  1324     1            2
141            1218          1.8         1      3.0   398     0            0
142            1537          2.5         0      1.0  3685     1            3
143             786          2.2         1      7.0  2390     1            2
144            1678          2.1         0      3.0   278     0            0
145            1814          1.4         1      2.0  3556     0            3
146            1101          1.8         0      2.0  2196     1            1
147            1461          2.4         1      7.0  3799     0            3
148            1216          3.0         0      3.0  2268     1            2
149             506          1.6         0      1.0  2965     0            2
150             843          0.5         0      5.0  2341     1            1
151             742          2.2         1      7.0  3557     1            3
152            1692          2.1         0      6.0  1354     0            1
153            1485          1.0         0      2.0  2147     0            2
154            1547          2.9         1      2.0   505     1            0
155            1692          2.3         1      1.0  1394     0            1
156             637          2.3         0      4.0   374     1            0
157            1224          0.5         0      6.0   506     1            0
158            1356          2.8         0      6.0  3702     0            3
159            1840          0.5         1      1.0  1078     0            1
160            1481          0.7         1      5.0  2945     1            2
161             961          1.5         1      6.0  2981     1            2
162            1296          0.9         1      5.0   490     1            0
163            1193          0.9         0      1.0   536     1            0
164            1441          2.1         1      8.0  2317     1            2
165             517          1.4         1      4.0  3704     1            3
166             748          1.7         0      8.0  2126     0            1
167            1126          2.4         0      6.0  2050     1            2
168            1572          0.6         0      7.0  2462     0            3
169            1569          2.8         1      4.0  1260     0            1
170            1270          0.6         1      7.0  3770     0            3
171            1854          3.0         0      5.0  1886     0            1
172             625          1.2         1      4.0  3323     1            2
173            1577          0.5         1      5.0  2060     0            2
174             534          0.5         1      5.0  3926     0            3
175             946          1.7         1      6.0  2177     1            2
176             685          0.5         0      7.0   728     1            0
177            1949          1.3         1      5.0  2478     0            3
178             947          0.8         1      2.0  2842     0            2
179             801          2.2         1      7.0  1617     1            1
180             703          2.7         0      1.0  1472     0            0
181            1165          2.4         0      6.0   764     0            0
182            1082          0.8         0      8.0  2337     1            2
183             959          2.6         1      4.0  3965     0            3
184            1502          1.2         0      5.0  3693     0            3
185            1380          2.1         1      3.0   797     0            0
186            1266          0.5         0      6.0  1687     0            2
187            1934          2.6         1      1.0  2940     1            3
188            1905          0.5         0      1.0  1545     0            1
189            1831          1.4         1      5.0  3834     1            3
190             596          1.4         0      1.0  2505     0            1
191            1562          1.3         1      5.0  2243     0            2
192            1490          0.5         1      8.0  3600     1            3
193            1523          2.4         0      2.0  3971     1            3
194             640          0.6         0      4.0  2844     0            2
195            1526          2.1         0      7.0  2227     0            2
196            1989          2.5         1      3.0  1665     1            2
197            1308          1.9         0      3.0  3355     1            3
198             609          0.5         0      4.0  1866     1            1
199            1905          0.6         1      3.0  1287     0            1
200            1703          0.5         0      1.0  1046     1            0
201            1445          2.4         1      7.0  1441     1            1
202            1087          1.3         0      3.0   690     1            0
203             671          0.9         1      7.0  2504     0            2
204            1472          2.3         0      6.0  2677     0            2
205             765          0.5         1      8.0  2243     1            2
206            1642          0.5         1      6.0  2984     1            2
207            1265          1.5         0      5.0  1362     1            1
208             664          1.1         1      7.0  3629     1            3
209            1277          0.5         1      6.0  3559     0            3
210            1395          1.8         1      3.0  2571     1            2
211            1539          2.6         0      8.0  2107     1            2
212            1049          2.2         0      5.0  1022     0            0
213            1827          1.7         0      5.0  2844     0            2
214             903          1.0         1      1.0   711     0            0
215            1987          0.5         0      3.0  3117     1            3
216            1154          1.2         1      8.0   978     1            0
217            1336          0.9         0      5.0  1869     1            1
218            1886          0.5         0      3.0  1179     1            1
219            1551          1.1         0      5.0  3844     0            3
220             850          1.6         1      5.0   593     1            0
221             660          0.5         0      2.0   588     1            0
222            1225          2.1         1      4.0  3836     0            3
223            1452          0.5         1      6.0  2669     0            2
224            1686          2.8         1      4.0  2958     0            3
225            1634          1.4         0      2.0  3031     1            3
226            1708          2.4         1      1.0  3388     1            3
227            1151          2.9         1      8.0  2377     0            2
228            1578          1.9         1      4.0  2458     1            2
229            1689          1.8         0      3.0  2766     1            3
230            1488          0.5         0      5.0  3054     0            3
231            1313          1.8         1      1.0  3791     1            3
232            1715          1.0         1      8.0   625     0            0
233            1442          1.0         1      3.0  2227     0            1
234             528          1.7         0      2.0  3256     0            2
235            1523          1.8         0      1.0   707     0            0
236            1133          1.4         0      5.0  1457     1            1
237            1718          2.5         1      5.0  3755     1            3
238            1330          0.5         0      7.0  1733     1            1
239            1799          0.5         0      4.0   720     1            0
240             633          2.2         0      8.0  3560     1            2
241             724          2.7         1      7.0  2311     0            2
242             822          0.5         0      6.0  3846     0            3
243            1918          1.9         0      5.0  1717     1            2
244            1891          2.8         0      7.0  3704     0            3
245            1373          1.0         1      7.0  3800     0            3
246             862          0.8         1      2.0   278     1            0
247            1273          1.0         0      4.0  1767     0            1
248             957          2.5         0      5.0  1846     1            1
249            1617          1.3         1      2.0   829     0            0
250             893          2.5         1      2.0  2986     1            2
251            1210          0.5         0      5.0  2394     0            2
252             708          2.7         1      8.0  2169     1            1
253             835          1.1         1      4.0  1181     1            0
254            1450          2.7         1      1.0   575     0            0
255             973          1.5         0      7.0  2977     0            2
256             601          1.4         0      4.0   532     1            0
257             507          0.5         1      7.0  1702     1            1

In [20]:
# pip install matplotlib

In [21]:
pd.reset_option("all")

C:\Users\ganga\AppData\Local\Temp\ipykernel_25840\3365680546.py:1: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option("all")
C:\Users\ganga\AppData\Local\Temp\ipykernel_25840\3365680546.py:1: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option("all")

## fetch 100 to 200 records

In [22]:
mobiledataset_df[100:200]

     battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
100           1883          0.5         0      6.0  2600     0            3
101           1732          1.1         0      8.0  1308     1            1
102            543          0.5         0      5.0  2413     0            1
103           1939          2.8         1      4.0  1047     0            0
104            553          2.4         1      7.0  1204     1            0
..             ...          ...       ...      ...   ...   ...          ...
195           1526          2.1         0      7.0  2227     0            2
196           1989          2.5         1      3.0  1665     1            2
197           1308          1.9         0      3.0  3355     1            3
198            609          0.5         0      4.0  1866     1            1
199           1905          0.6         1      3.0  1287     0            1

[100 rows x 7 columns]

## print alternate elements from a dataframe

In [23]:
mobiledataset_df[::2]

      battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0               842          2.2         0      NaN  2549     1            1
2               563          0.5         1      NaN  2603     0            2
4              1821          1.2         0      2.0  1411     0            1
6              1821          1.7         0      8.0  3220     1            3
8              1445          0.5         0      7.0  1099     0            0
...             ...          ...       ...      ...   ...   ...          ...
1990           1617          2.4         0      1.0   296     0            0
1992            674          2.9         1      3.0  1180     1            0
1994            858          2.2         0      1.0  3978     0            3
1996           1965          2.6         1      4.0  2032     1            2
1998           1512          0.9         0      5.0   869     1            0

[1000 rows x 7 columns]

## print dataframe in reverse order

In [24]:
mobiledataset_df[::-1]

      battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
1999            510          2.0         1      6.0  3919     1            3
1998           1512          0.9         0      5.0   869     1            0
1997           1911          0.9         1      8.0  3057     0            3
1996           1965          2.6         1      4.0  2032     1            2
1995            794          0.5         1      6.0   668     0            0
...             ...          ...       ...      ...   ...   ...          ...
4              1821          1.2         0      2.0  1411     0            1
3               615          2.5         0      6.0  2769     0            2
2               563          0.5         1      NaN  2603     0            2
1              1021          0.5         1      NaN  2631     0            2
0               842          2.2         0      NaN  2549     1            1

[2000 rows x 7 columns]

## fetch single column

In [25]:
mobiledataset_df['battery_power']

0        842
1       1021
2        563
3        615
4       1821
        ...
1995     794
1996    1965
1997    1911
1998    1512
1999     510
Name: battery_power, Length: 2000, dtype: int64

In [26]:
mobiledataset_df[['battery_power','clock_speed']]

      battery_power  clock_speed
0               842          2.2
1              1021          0.5
2               563          0.5
3               615          2.5
4              1821          1.2
...             ...          ...
1995            794          0.5
1996           1965          2.6
1997           1911          0.9
1998           1512          0.9
1999            510          2.0

[2000 rows x 2 columns]

In [27]:
mobiledataset_df[0:1]

   battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0            842          2.2         0      NaN  2549     1            1

In [28]:
mobiledataset_df.iloc[0:1]

   battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0            842          2.2         0      NaN  2549     1            1

In [29]:
mobiledataset_df.iloc[0]

battery_power     842.0
clock_speed         2.2
dual_sim            0.0
n_cores             NaN
ram              2549.0
wifi                1.0
price_range         1.0
Name: 0, dtype: float64

In [30]:
mobiledataset_df.iloc[0:100]

    battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0             842          2.2         0      NaN  2549     1            1
1            1021          0.5         1      NaN  2631     0            2
2             563          0.5         1      NaN  2603     0            2
3             615          2.5         0      6.0  2769     0            2
4            1821          1.2         0      2.0  1411     0            1
..            ...          ...       ...      ...   ...   ...          ...
95           1137          1.0         0      3.0  3616     1            3
96           1355          2.3         0      5.0   880     0            0
97           1665          0.5         0      6.0  1601     0            2
98            657          2.5         0      2.0  1412     0            0
99            593          0.5         0      7.0  1692     0            1

[100 rows x 7 columns]

In [31]:
mobiledataset_df.iloc[0:100:2]

    battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0             842          2.2         0      NaN  2549     1            1
2             563          0.5         1      NaN  2603     0            2
4            1821          1.2         0      2.0  1411     0            1
6            1821          1.7         0      8.0  3220     1            3
8            1445          0.5         0      7.0  1099     0            0
10            769          2.9         1      5.0  3946     0            3
12           1815          2.8         0      4.0  1482     0            1
14           1866          0.5         0      1.0   373     1            0
16            838          0.5         0      8.0  3554     1            3
18           1131          0.5         1      5.0  1835     0            1
20            772          1.1         1      7.0  2819     0            3
22           1949          2.6         1      4.0  1433     1            1
24            503          1.2         1      3.0  2583     0            1
26            519          1.6         1      4.0  3763     1            3
28           1453          1.6         1      2.0  2373     1            2
30           1579          0.5         1      7.0  3532     1            3
32           1319          0.9         0      1.0  2227     1            1
34            644          2.7         0      8.0  1262     0            0
36            589          2.3         1      4.0  2113     1            1
38            790          2.0         1      6.0  3169     1            2
40           1347          2.9         0      1.0  2484     1            2
42           1253          0.5         1      2.0  1878     0            1
44           1195          2.8         0      2.0   504     0            0
46           1723          1.1         1      8.0  3587     0            3
48            578          2.6         1      8.0  1270     1            0
50           1547          3.0         1      3.0  2059     1            2
52           1654          1.5         1      2.0  3112     0            3
54           1073          0.5         1      7.0  2908     0            2
56            823          2.7         1      8.0   905     1            0
58           1757          0.5         0      6.0  2056     0            1
60           1484          3.0         0      3.0  1457     0            1
62           1156          1.2         1      2.0   470     0            0
64            702          2.6         1      3.0  2955     0            2
66           1358          0.5         0      4.0  3068     0            3
68           1242          1.1         1      2.0  1050     1            0
70           1448          0.5         1      7.0  3378     1            3
72            605          1.0         0      3.0   392     0            0
74            797          2.9         1      4.0   590     0            0
76           1114          2.8         0      3.0   907     0            0
78           1199          2.5         1      4.0  3448     1            3
80           1589          0.6         1      7.0  3464     1            3
82           1510          0.9         1      5.0  3484     1            3
84           1127          2.9         1      1.0  2048     1            1
86           1496          2.0         1      5.0   854     1            0
88            668          0.5         1      5.0  2746     1            2
90           1724          2.0         1      3.0  2822     0            3
92            885          2.3         1      7.0  1410     1            0
94           1322          1.7         1      3.0  1418     0            1
96           1355          2.3         0      5.0   880     0            0
98            657          2.5         0      2.0  1412     0            0

In [32]:
mobiledataset_df.iloc[0::2,::2]

      battery_power  dual_sim   ram  price_range
0               842         0  2549            1
2               563         1  2603            2
4              1821         0  1411            1
6              1821         0  3220            3
8              1445         0  1099            0
...             ...       ...   ...          ...
1990           1617         0   296            0
1992            674         1  1180            0
1994            858         0  3978            3
1996           1965         1  2032            2
1998           1512         0   869            0

[1000 rows x 4 columns]

In [33]:
mobiledataset_df.iloc[0:,::-1]

      price_range  wifi   ram  n_cores  dual_sim  clock_speed  battery_power
0               1     1  2549      NaN         0          2.2            842
1               2     0  2631      NaN         1          0.5           1021
2               2     0  2603      NaN         1          0.5            563
3               2     0  2769      6.0         0          2.5            615
4               1     0  1411      2.0         0          1.2           1821
...           ...   ...   ...      ...       ...          ...            ...
1995            0     0   668      6.0         1          0.5            794
1996            2     1  2032      4.0         1          2.6           1965
1997            3     0  3057      8.0         1          0.9           1911
1998            0     1   869      5.0         0          0.9           1512
1999            3     1  3919      6.0         1          2.0            510

[2000 rows x 7 columns]

In [34]:
mobiledataset_df.loc[0:,'battery_power']

0        842
1       1021
2        563
3        615
4       1821
        ...
1995     794
1996    1965
1997    1911
1998    1512
1999     510
Name: battery_power, Length: 2000, dtype: int64

In [35]:
mobiledataset_df.loc[0:,['battery_power','wifi']]

      battery_power  wifi
0               842     1
1              1021     0
2               563     0
3               615     0
4              1821     0
...             ...   ...
1995            794     0
1996           1965     1
1997           1911     0
1998           1512     1
1999            510     1

[2000 rows x 2 columns]

In [36]:
## drop the records

In [37]:
mobiledataset_df.drop(2)

      battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0               842          2.2         0      NaN  2549     1            1
1              1021          0.5         1      NaN  2631     0            2
3               615          2.5         0      6.0  2769     0            2
4              1821          1.2         0      2.0  1411     0            1
5              1859          0.5         1      1.0  1067     0            1
...             ...          ...       ...      ...   ...   ...          ...
1995            794          0.5         1      6.0   668     0            0
1996           1965          2.6         1      4.0  2032     1            2
1997           1911          0.9         1      8.0  3057     0            3
1998           1512          0.9         0      5.0   869     1            0
1999            510          2.0         1      6.0  3919     1            3

[1999 rows x 7 columns]

In [38]:
mobiledataset_df.drop([3,5,6])

      battery_power  clock_speed  dual_sim  n_cores   ram  wifi  price_range
0               842          2.2         0      NaN  2549     1            1
1              1021          0.5         1      NaN  2631     0            2
2               563          0.5         1      NaN  2603     0            2
4              1821          1.2         0      2.0  1411     0            1
7              1954          0.5         1      4.0   700     1            0
...             ...          ...       ...      ...   ...   ...          ...
1995            794          0.5         1      6.0   668     0            0
1996           1965          2.6         1      4.0  2032     1            2
1997           1911          0.9         1      8.0  3057     0            3
1998           1512          0.9         0      5.0   869     1            0
1999            510          2.0         1      6.0  3919     1            3

[1997 rows x 7 columns]

In [39]:
mobiledataset_df.drop('battery_power',axis=1)

      clock_speed  dual_sim  n_cores   ram  wifi  price_range
0             2.2         0      NaN  2549     1            1
1             0.5         1      NaN  2631     0            2
2             0.5         1      NaN  2603     0            2
3             2.5         0      6.0  2769     0            2
4             1.2         0      2.0  1411     0            1
...           ...       ...      ...   ...   ...          ...
1995          0.5         1      6.0   668     0            0
1996          2.6         1      4.0  2032     1            2
1997          0.9         1      8.0  3057     0            3
1998          0.9         0      5.0   869     1            0
1999          2.0         1      6.0  3919     1            3

[2000 rows x 6 columns]

In [40]:
mobiledataset_df.drop(['battery_power','ram'],axis=1)

      clock_speed  dual_sim  n_cores  wifi  price_range
0             2.2         0      NaN     1            1
1             0.5         1      NaN     0            2
2             0.5         1      NaN     0            2
3             2.5         0      6.0     0            2
4             1.2         0      2.0     0            1
...           ...       ...      ...   ...          ...
1995          0.5         1      6.0     0            0
1996          2.6         1      4.0     1            2
1997          0.9         1      8.0     0            3
1998          0.9         0      5.0     1            0
1999          2.0         1      6.0     1            3

[2000 rows x 5 columns]

In [41]:
mobiledataset_df.isnull()

      battery_power  clock_speed  dual_sim  n_cores    ram   wifi  price_range
0             False        False     False     True  False  False        False
1             False        False     False     True  False  False        False
2             False        False     False     True  False  False        False
3             False        False     False    False  False  False        False
4             False        False     False    False  False  False        False
...             ...          ...       ...      ...    ...    ...          ...
1995          False        False     False    False  False  False        False
1996          False        False     False    False  False  False        False
1997          False        False     False    False  False  False        False
1998          False        False     False    False  False  False        False
1999          False        False     False    False  False  False        False

[2000 rows x 7 columns]

In [42]:
mobiledataset_df.isnull().sum()

battery_power    0
clock_speed      0
dual_sim         0
n_cores          3
ram              0
wifi             0
price_range      0
dtype: int64

In [43]:
mobiledataset_df.isnull().sum().sum()

np.int64(3)

In [44]:
# Aggregate Functions
# The aggregate function is used to aggregate using one or more operations over the specified axis/columns.
# The aggregate functions in pandas
# count, sum, mean, median, mode, min, max

# Aggregate functions

In [45]:
# pip install openpyxl

In [46]:
patient_df = pd.read_excel('PatientData.xlsx')

In [47]:
patient_df

     Name Location   Age  Score BloodGroup  eligible
0    jhon       CA   NaN    9.0       B+ve         1
1    mike       LA  32.0    9.0       B+ve         1
2    dane       NY   NaN    8.0       A-ve         1
3   peter       NY  33.0    2.0       O+ve         1
4   macey      NaN   NaN    NaN       O-ve         1
5   chimp       CA  53.0    4.0       A-ve         1
6   jacob    TEXAS  34.0    5.0       A+ve         1
7  daniel       DC  21.0    1.0      AB-ve         1

In [48]:
patient_df.columns

Index(['Name', 'Location', 'Age', 'Score', 'BloodGroup', 'eligible'], dtype='str')

In [49]:
patient_df['Age'].count()

np.int64(5)

In [50]:
patient_df['BloodGroup'].count()

np.int64(8)

In [51]:
patient_df['Age'].max()

np.float64(53.0)

In [52]:
patient_df['Age'].min()

np.float64(21.0)

In [53]:
patient_df['Age'].sum()

np.float64(173.0)

In [54]:
patient_df['Age'].mean()

np.float64(34.6)

In [55]:
patient_df['Age'].median()

np.float64(33.0)

In [56]:
patient_df['Score'].mode()

0    9.0
Name: Score, dtype: float64

# sorting the columns

In [57]:
patient_df['Age'].sort_values()

7    21.0
1    32.0
3    33.0
6    34.0
5    53.0
0     NaN
2     NaN
4     NaN
Name: Age, dtype: float64

In [58]:
patient_df['Age'].sort_values(ascending=False)

5    53.0
6    34.0
3    33.0
1    32.0
7    21.0
0     NaN
2     NaN
4     NaN
Name: Age, dtype: float64

In [59]:
sorting_patient_df=patient_df.sort_values(by='Age')
sorting_patient_df

     Name Location   Age  Score BloodGroup  eligible
7  daniel       DC  21.0    1.0      AB-ve         1
1    mike       LA  32.0    9.0       B+ve         1
3   peter       NY  33.0    2.0       O+ve         1
6   jacob    TEXAS  34.0    5.0       A+ve         1
5   chimp       CA  53.0    4.0       A-ve         1
0    jhon       CA   NaN    9.0       B+ve         1
2    dane       NY   NaN    8.0       A-ve         1
4   macey      NaN   NaN    NaN       O-ve         1

In [60]:
sorting_patient_df_desc=patient_df.sort_values(by='Age')
sorting_patient_df_desc

     Name Location   Age  Score BloodGroup  eligible
7  daniel       DC  21.0    1.0      AB-ve         1
1    mike       LA  32.0    9.0       B+ve         1
3   peter       NY  33.0    2.0       O+ve         1
6   jacob    TEXAS  34.0    5.0       A+ve         1
5   chimp       CA  53.0    4.0       A-ve         1
0    jhon       CA   NaN    9.0       B+ve         1
2    dane       NY   NaN    8.0       A-ve         1
4   macey      NaN   NaN    NaN       O-ve         1

In [61]:
sorting_patient_df_desc=patient_df.sort_values(by='Age',ascending=False)
sorting_patient_df_desc

     Name Location   Age  Score BloodGroup  eligible
5   chimp       CA  53.0    4.0       A-ve         1
6   jacob    TEXAS  34.0    5.0       A+ve         1
3   peter       NY  33.0    2.0       O+ve         1
1    mike       LA  32.0    9.0       B+ve         1
7  daniel       DC  21.0    1.0      AB-ve         1
0    jhon       CA   NaN    9.0       B+ve         1
2    dane       NY   NaN    8.0       A-ve         1
4   macey      NaN   NaN    NaN       O-ve         1

In [62]:
sorting_patient_df=patient_df.sort_values(by=['Score','Age'],ascending=False)
sorting_patient_df

     Name Location   Age  Score BloodGroup  eligible
1    mike       LA  32.0    9.0       B+ve         1
0    jhon       CA   NaN    9.0       B+ve         1
2    dane       NY   NaN    8.0       A-ve         1
6   jacob    TEXAS  34.0    5.0       A+ve         1
5   chimp       CA  53.0    4.0       A-ve         1
3   peter       NY  33.0    2.0       O+ve         1
7  daniel       DC  21.0    1.0      AB-ve         1
4   macey      NaN   NaN    NaN       O-ve         1

# filtering the records

In [63]:
student_df = pd.read_excel('student_records.xlsx')
student_df

       Name  Age      Place BloodGroup  Score Grade
0     Alice   22    Lucknow         O+     83     C
1       Bob   22  Ahmedabad        AB+     46     C
2   Charlie   21     Mumbai        AB+     79     A
3     David   24       Pune        AB-     81     C
4       Eva   19  Ahmedabad         O-     46     A
5     Frank   25  Ahmedabad         B+     60     B
6     Grace   22    Kolkata         A+     42     E
7     Helen   25  Ahmedabad         O+     58     B
8       Ian   23    Kolkata         A+     63     E
9     Julia   19    Kolkata        AB+     56     B
10    Kevin   19  Ahmedabad         A-     94     A
11    Laura   25    Lucknow         A-     47     B
12     Mike   18    Kolkata        AB-     56     C
13     Nina   25       Pune         A+     77     B
14    Oscar   23  Ahmedabad         A-     93     D
15    Paula   25      Delhi        AB+     71     B
16  Quentin   21     Mumbai         O+     71     D
17   Rachel   19  Bangalore         B-     91     A
18    Steve   21    Lucknow         O+     69     C
19     Tina   20  Bangalore         B-     78     D

In [64]:
student_df['Age'] > 20

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9     False
10    False
11     True
12    False
13     True
14     True
15     True
16     True
17    False
18     True
19    False
Name: Age, dtype: bool

In [65]:
student_df[student_df['Age'] > 20]

       Name  Age      Place BloodGroup  Score Grade
0     Alice   22    Lucknow         O+     83     C
1       Bob   22  Ahmedabad        AB+     46     C
2   Charlie   21     Mumbai        AB+     79     A
3     David   24       Pune        AB-     81     C
5     Frank   25  Ahmedabad         B+     60     B
6     Grace   22    Kolkata         A+     42     E
7     Helen   25  Ahmedabad         O+     58     B
8       Ian   23    Kolkata         A+     63     E
11    Laura   25    Lucknow         A-     47     B
13     Nina   25       Pune         A+     77     B
14    Oscar   23  Ahmedabad         A-     93     D
15    Paula   25      Delhi        AB+     71     B
16  Quentin   21     Mumbai         O+     71     D
18    Steve   21    Lucknow         O+     69     C

In [66]:
student_df[student_df['Score'] < 75]

       Name  Age      Place BloodGroup  Score Grade
1       Bob   22  Ahmedabad        AB+     46     C
4       Eva   19  Ahmedabad         O-     46     A
5     Frank   25  Ahmedabad         B+     60     B
6     Grace   22    Kolkata         A+     42     E
7     Helen   25  Ahmedabad         O+     58     B
8       Ian   23    Kolkata         A+     63     E
9     Julia   19    Kolkata        AB+     56     B
11    Laura   25    Lucknow         A-     47     B
12     Mike   18    Kolkata        AB-     56     C
15    Paula   25      Delhi        AB+     71     B
16  Quentin   21     Mumbai         O+     71     D
18    Steve   21    Lucknow         O+     69     C

In [67]:
student_df[student_df['Place'] == 'Ahmedabad']

     Name  Age      Place BloodGroup  Score Grade
1     Bob   22  Ahmedabad        AB+     46     C
4     Eva   19  Ahmedabad         O-     46     A
5   Frank   25  Ahmedabad         B+     60     B
7   Helen   25  Ahmedabad         O+     58     B
10  Kevin   19  Ahmedabad         A-     94     A
14  Oscar   23  Ahmedabad         A-     93     D

In [68]:
student_df[student_df['Place'] != 'Kolkata']

       Name  Age      Place BloodGroup  Score Grade
0     Alice   22    Lucknow         O+     83     C
1       Bob   22  Ahmedabad        AB+     46     C
2   Charlie   21     Mumbai        AB+     79     A
3     David   24       Pune        AB-     81     C
4       Eva   19  Ahmedabad         O-     46     A
5     Frank   25  Ahmedabad         B+     60     B
7     Helen   25  Ahmedabad         O+     58     B
10    Kevin   19  Ahmedabad         A-     94     A
11    Laura   25    Lucknow         A-     47     B
13     Nina   25       Pune         A+     77     B
14    Oscar   23  Ahmedabad         A-     93     D
15    Paula   25      Delhi        AB+     71     B
16  Quentin   21     Mumbai         O+     71     D
17   Rachel   19  Bangalore         B-     91     A
18    Steve   21    Lucknow         O+     69     C
19     Tina   20  Bangalore         B-     78     D

# fetch all students whose score is greater than 50 and less than 80

In [69]:
student_df[student_df['Score'] > 50]

       Name  Age      Place BloodGroup  Score Grade
0     Alice   22    Lucknow         O+     83     C
2   Charlie   21     Mumbai        AB+     79     A
3     David   24       Pune        AB-     81     C
5     Frank   25  Ahmedabad         B+     60     B
7     Helen   25  Ahmedabad         O+     58     B
8       Ian   23    Kolkata         A+     63     E
9     Julia   19    Kolkata        AB+     56     B
10    Kevin   19  Ahmedabad         A-     94     A
12     Mike   18    Kolkata        AB-     56     C
13     Nina   25       Pune         A+     77     B
14    Oscar   23  Ahmedabad         A-     93     D
15    Paula   25      Delhi        AB+     71     B
16  Quentin   21     Mumbai         O+     71     D
17   Rachel   19  Bangalore         B-     91     A
18    Steve   21    Lucknow         O+     69     C
19     Tina   20  Bangalore         B-     78     D

In [70]:
student_df[student_df['Score'] < 80]

       Name  Age      Place BloodGroup  Score Grade
1       Bob   22  Ahmedabad        AB+     46     C
2   Charlie   21     Mumbai        AB+     79     A
4       Eva   19  Ahmedabad         O-     46     A
5     Frank   25  Ahmedabad         B+     60     B
6     Grace   22    Kolkata         A+     42     E
7     Helen   25  Ahmedabad         O+     58     B
8       Ian   23    Kolkata         A+     63     E
9     Julia   19    Kolkata        AB+     56     B
11    Laura   25    Lucknow         A-     47     B
12     Mike   18    Kolkata        AB-     56     C
13     Nina   25       Pune         A+     77     B
15    Paula   25      Delhi        AB+     71     B
16  Quentin   21     Mumbai         O+     71     D
18    Steve   21    Lucknow         O+     69     C
19     Tina   20  Bangalore         B-     78     D

In [71]:
student_df[(student_df['Score'] > 50) & (student_df['Score'] < 80)]

       Name  Age      Place BloodGroup  Score Grade
2   Charlie   21     Mumbai        AB+     79     A
5     Frank   25  Ahmedabad         B+     60     B
7     Helen   25  Ahmedabad         O+     58     B
8       Ian   23    Kolkata         A+     63     E
9     Julia   19    Kolkata        AB+     56     B
12     Mike   18    Kolkata        AB-     56     C
13     Nina   25       Pune         A+     77     B
15    Paula   25      Delhi        AB+     71     B
16  Quentin   21     Mumbai         O+     71     D
18    Steve   21    Lucknow         O+     69     C
19     Tina   20  Bangalore         B-     78     D

# fetch all students whose blood group is A positive and greater than 80

In [72]:
student_df[(student_df['BloodGroup'] == 'A+') & (student_df['Score'] > 70)]

    Name  Age Place BloodGroup  Score Grade
13  Nina   25  Pune         A+     77     B

In [73]:
# fetch

In [74]:
student_df[(student_df['Place'] != 'Kolkota') | (student_df['Score'] > 80)]

       Name  Age      Place BloodGroup  Score Grade
0     Alice   22    Lucknow         O+     83     C
1       Bob   22  Ahmedabad        AB+     46     C
2   Charlie   21     Mumbai        AB+     79     A
3     David   24       Pune        AB-     81     C
4       Eva   19  Ahmedabad         O-     46     A
5     Frank   25  Ahmedabad         B+     60     B
6     Grace   22    Kolkata         A+     42     E
7     Helen   25  Ahmedabad         O+     58     B
8       Ian   23    Kolkata         A+     63     E
9     Julia   19    Kolkata        AB+     56     B
10    Kevin   19  Ahmedabad         A-     94     A
11    Laura   25    Lucknow         A-     47     B
12     Mike   18    Kolkata        AB-     56     C
13     Nina   25       Pune         A+     77     B
14    Oscar   23  Ahmedabad         A-     93     D
15    Paula   25      Delhi        AB+     71     B
16  Quentin   21     Mumbai         O+     71     D
17   Rachel   19  Bangalore         B-     91     A
18    Steve   21    Lucknow         O+     69     C
19     Tina   20  Bangalore         B-     78     D

In [75]:
student_df[student_df['Grade'] == 'A']

       Name  Age      Place BloodGroup  Score Grade
2   Charlie   21     Mumbai        AB+     79     A
4       Eva   19  Ahmedabad         O-     46     A
10    Kevin   19  Ahmedabad         A-     94     A
17   Rachel   19  Bangalore         B-     91     A

In [76]:
student_df[student_df['Grade'] == 'A'] ['Name']

2     Charlie
4         Eva
10      Kevin
17     Rachel
Name: Name, dtype: str

In [77]:
student_df[student_df['Place'].str.startswith('K')]

     Name  Age    Place BloodGroup  Score Grade
6   Grace   22  Kolkata         A+     42     E
8     Ian   23  Kolkata         A+     63     E
9   Julia   19  Kolkata        AB+     56     B
12   Mike   18  Kolkata        AB-     56     C

In [78]:
# fetch

In [79]:
student_df[student_df['Name'].str.endswith('a')]

     Name  Age      Place BloodGroup  Score Grade
4     Eva   19  Ahmedabad         O-     46     A
9   Julia   19    Kolkata        AB+     56     B
11  Laura   25    Lucknow         A-     47     B
13   Nina   25       Pune         A+     77     B
15  Paula   25      Delhi        AB+     71     B
19   Tina   20  Bangalore         B-     78     D

In [80]:
# Display the Records whose score is maximum

In [81]:
student_df[(student_df['Score']) == (student_df['Score']).max()]

     Name  Age      Place BloodGroup  Score Grade
10  Kevin   19  Ahmedabad         A-     94     A

In [82]:
student_df[(student_df['Age']) == (student_df['Age']).min()]

    Name  Age    Place BloodGroup  Score Grade
12  Mike   18  Kolkata        AB-     56     C

In [83]:
# drop whose grade is drop e grade students

In [84]:
student_df.drop(student_df[student_df['Grade']=='E'].index)

       Name  Age      Place BloodGroup  Score Grade
0     Alice   22    Lucknow         O+     83     C
1       Bob   22  Ahmedabad        AB+     46     C
2   Charlie   21     Mumbai        AB+     79     A
3     David   24       Pune        AB-     81     C
4       Eva   19  Ahmedabad         O-     46     A
5     Frank   25  Ahmedabad         B+     60     B
7     Helen   25  Ahmedabad         O+     58     B
9     Julia   19    Kolkata        AB+     56     B
10    Kevin   19  Ahmedabad         A-     94     A
11    Laura   25    Lucknow         A-     47     B
12     Mike   18    Kolkata        AB-     56     C
13     Nina   25       Pune         A+     77     B
14    Oscar   23  Ahmedabad         A-     93     D
15    Paula   25      Delhi        AB+     71     B
16  Quentin   21     Mumbai         O+     71     D
17   Rachel   19  Bangalore         B-     91     A
18    Steve   21    Lucknow         O+     69     C
19     Tina   20  Bangalore         B-     78     D

In [85]:
student_df = pd.read_excel('student_records_with_nan.xlsx')
student_df

       Name   Age      Place  Score Grade
0     Alice  20.0     Mumbai   85.0     A
1       Bob  21.0      Delhi    NaN     B
2   Charlie   NaN    Chennai   75.0     C
3     David  22.0        NaN   90.0     A
4       Eva  23.0  Hyderabad   65.0   NaN
5       NaN  24.0  Bangalore   70.0     B
6     Grace   NaN       Pune    NaN     C
7       NaN   NaN        NaN    NaN   NaN
8     Helen  21.0  Ahmedabad   88.0   NaN
9       Ian  20.0        NaN   60.0     D
10    Julia  22.0    Lucknow    NaN     A

In [86]:
student_df.isnull().sum()

Name     2
Age      3
Place    3
Score    4
Grade    3
dtype: int64

In [87]:
student_df.isnull().sum().sum()

np.int64(15)

## dropna and fillna

In [88]:
student_df.dropna() # drop the row if empty data is present

    Name   Age   Place  Score Grade
0  Alice  20.0  Mumbai   85.0     A

In [89]:
student_df.dropna(how='all')

       Name   Age      Place  Score Grade
0     Alice  20.0     Mumbai   85.0     A
1       Bob  21.0      Delhi    NaN     B
2   Charlie   NaN    Chennai   75.0     C
3     David  22.0        NaN   90.0     A
4       Eva  23.0  Hyderabad   65.0   NaN
5       NaN  24.0  Bangalore   70.0     B
6     Grace   NaN       Pune    NaN     C
8     Helen  21.0  Ahmedabad   88.0   NaN
9       Ian  20.0        NaN   60.0     D
10    Julia  22.0    Lucknow    NaN     A

In [90]:
student_df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [91]:
student_df.dropna(axis = 0)

    Name   Age   Place  Score Grade
0  Alice  20.0  Mumbai   85.0     A

In [92]:
student_df.dropna(subset="Name")

       Name   Age      Place  Score Grade
0     Alice  20.0     Mumbai   85.0     A
1       Bob  21.0      Delhi    NaN     B
2   Charlie   NaN    Chennai   75.0     C
3     David  22.0        NaN   90.0     A
4       Eva  23.0  Hyderabad   65.0   NaN
6     Grace   NaN       Pune    NaN     C
8     Helen  21.0  Ahmedabad   88.0   NaN
9       Ian  20.0        NaN   60.0     D
10    Julia  22.0    Lucknow    NaN     A

In [93]:
student_df.dropna(subset=["Name", "Age"])

     Name   Age      Place  Score Grade
0   Alice  20.0     Mumbai   85.0     A
1     Bob  21.0      Delhi    NaN     B
3   David  22.0        NaN   90.0     A
4     Eva  23.0  Hyderabad   65.0   NaN
8   Helen  21.0  Ahmedabad   88.0   NaN
9     Ian  20.0        NaN   60.0     D
10  Julia  22.0    Lucknow    NaN     A

In [94]:
student_df.dropna(subset="Name",inplace=True)

In [95]:
student_df

       Name   Age      Place  Score Grade
0     Alice  20.0     Mumbai   85.0     A
1       Bob  21.0      Delhi    NaN     B
2   Charlie   NaN    Chennai   75.0     C
3     David  22.0        NaN   90.0     A
4       Eva  23.0  Hyderabad   65.0   NaN
6     Grace   NaN       Pune    NaN     C
8     Helen  21.0  Ahmedabad   88.0   NaN
9       Ian  20.0        NaN   60.0     D
10    Julia  22.0    Lucknow    NaN     A

In [96]:
student_df

       Name   Age      Place  Score Grade
0     Alice  20.0     Mumbai   85.0     A
1       Bob  21.0      Delhi    NaN     B
2   Charlie   NaN    Chennai   75.0     C
3     David  22.0        NaN   90.0     A
4       Eva  23.0  Hyderabad   65.0   NaN
6     Grace   NaN       Pune    NaN     C
8     Helen  21.0  Ahmedabad   88.0   NaN
9       Ian  20.0        NaN   60.0     D
10    Julia  22.0    Lucknow    NaN     A

In [97]:
filled_data={
    'Age':student_df['Age'].mean(),
    'Place':student_df['Place'].mode()[2],
    'Score':student_df['Score'].mean(),
}
filled_data

{'Age': np.float64(21.285714285714285),
 'Place': 'Delhi',
 'Score': np.float64(77.16666666666667)}

In [98]:
student_df.fillna(filled_data,inplace=True)

       Name        Age      Place      Score Grade
0     Alice  20.000000     Mumbai  85.000000     A
1       Bob  21.000000      Delhi  77.166667     B
2   Charlie  21.285714    Chennai  75.000000     C
3     David  22.000000      Delhi  90.000000     A
4       Eva  23.000000  Hyderabad  65.000000   NaN
6     Grace  21.285714       Pune  77.166667     C
8     Helen  21.000000  Ahmedabad  88.000000   NaN
9       Ian  20.000000      Delhi  60.000000     D
10    Julia  22.000000    Lucknow  77.166667     A

In [99]:
student_df

       Name        Age      Place      Score Grade
0     Alice  20.000000     Mumbai  85.000000     A
1       Bob  21.000000      Delhi  77.166667     B
2   Charlie  21.285714    Chennai  75.000000     C
3     David  22.000000      Delhi  90.000000     A
4       Eva  23.000000  Hyderabad  65.000000   NaN
6     Grace  21.285714       Pune  77.166667     C
8     Helen  21.000000  Ahmedabad  88.000000   NaN
9       Ian  20.000000      Delhi  60.000000     D
10    Julia  22.000000    Lucknow  77.166667     A

In [100]:
student_df['Age']=student_df['Age'].astype(int)

In [101]:
student_df

       Name  Age      Place      Score Grade
0     Alice   20     Mumbai  85.000000     A
1       Bob   21      Delhi  77.166667     B
2   Charlie   21    Chennai  75.000000     C
3     David   22      Delhi  90.000000     A
4       Eva   23  Hyderabad  65.000000   NaN
6     Grace   21       Pune  77.166667     C
8     Helen   21  Ahmedabad  88.000000   NaN
9       Ian   20      Delhi  60.000000     D
10    Julia   22    Lucknow  77.166667     A

In [102]:
student_df["Grade"].unique()

<StringArray>
['A', 'B', 'C', nan, 'D']
Length: 5, dtype: str

In [103]:
replace_dict = {"Grade":{"A":"A-Grade",
                        "B":"B-Grade",
                        "C":"C-Grade",
                        "D":"D-Grade"}}

In [104]:
student_df.replace(replace_dict,inplace=True)

       Name  Age      Place      Score    Grade
0     Alice   20     Mumbai  85.000000  A-Grade
1       Bob   21      Delhi  77.166667  B-Grade
2   Charlie   21    Chennai  75.000000  C-Grade
3     David   22      Delhi  90.000000  A-Grade
4       Eva   23  Hyderabad  65.000000      NaN
6     Grace   21       Pune  77.166667  C-Grade
8     Helen   21  Ahmedabad  88.000000      NaN
9       Ian   20      Delhi  60.000000  D-Grade
10    Julia   22    Lucknow  77.166667  A-Grade

In [105]:
student_df

       Name  Age      Place      Score    Grade
0     Alice   20     Mumbai  85.000000  A-Grade
1       Bob   21      Delhi  77.166667  B-Grade
2   Charlie   21    Chennai  75.000000  C-Grade
3     David   22      Delhi  90.000000  A-Grade
4       Eva   23  Hyderabad  65.000000      NaN
6     Grace   21       Pune  77.166667  C-Grade
8     Helen   21  Ahmedabad  88.000000      NaN
9       Ian   20      Delhi  60.000000  D-Grade
10    Julia   22    Lucknow  77.166667  A-Grade

In [106]:
student_df.to_excel("student_data_filled_records.xlsx",index=False)

In [107]:
# Example to replace the data
# To Replace mupltiple values
# df = pd.read_excel("pandaspractice.xlsx")
# df.repalce([0,'NY'],['Zero','NewYork'])

# concatenation

In [108]:
dict1 = {"name": ["ramesh","suresh","manish"],
        "age": [20,21,22]}
df1 = pd.DataFrame(dict1)
df1

     name  age
0  ramesh   20
1  suresh   21
2  manish   22

In [109]:
dict2 = {"name": ["simon","leo","ranidher"],
        "age": [25,26,27]}
df2 = pd.DataFrame(dict2)
df2

       name  age
0     simon   25
1       leo   26
2  ranidher   27

In [110]:
df=pd.concat([df1,df2],axis=1)
df

     name  age      name  age
0  ramesh   20     simon   25
1  suresh   21       leo   26
2  manish   22  ranidher   27

In [111]:
df=pd.concat([df1,df2])
df

       name  age
0    ramesh   20
1    suresh   21
2    manish   22
0     simon   25
1       leo   26
2  ranidher   27

# merge

In [112]:
data1 = {"id":[1,2,3,4,5,6],
        "name":["den","rome","luck","vignesh","peo","ganesh"]}
data2 = {"id":[6,7,8,9,10,11],
        "place":["Banglore","hyd","vijayawada","Lucknow","andhra","up"]}

In [113]:
df3 = pd.DataFrame(data1)
df4 = pd.DataFrame(data2)

In [114]:
df3

   id     name
0   1      den
1   2     rome
2   3     luck
3   4  vignesh
4   5      peo
5   6   ganesh

In [115]:
df4

   id       place
0   6    Banglore
1   7         hyd
2   8  vijayawada
3   9     Lucknow
4  10      andhra
5  11          up

In [116]:
merged_df = pd.merge(df3,df4,on='id')
merged_df

   id    name     place
0   6  ganesh  Banglore

In [117]:
merged_df = pd.merge(df3,df4,how='outer')
merged_df

    id     name       place
0    1      den         NaN
1    2     rome         NaN
2    3     luck         NaN
3    4  vignesh         NaN
4    5      peo         NaN
5    6   ganesh    Banglore
6    7      NaN         hyd
7    8      NaN  vijayawada
8    9      NaN     Lucknow
9   10      NaN      andhra
10  11      NaN          up

In [118]:
merged_df = pd.merge(df3,df4,on="id",how='left')
merged_df

   id     name     place
0   1      den       NaN
1   2     rome       NaN
2   3     luck       NaN
3   4  vignesh       NaN
4   5      peo       NaN
5   6   ganesh  Banglore

In [119]:
merged_df = pd.merge(df3,df4,on="id",how='right')
merged_df

   id    name       place
0   6  ganesh    Banglore
1   7     NaN         hyd
2   8     NaN  vijayawada
3   9     NaN     Lucknow
4  10     NaN      andhra
5  11     NaN          up

In [120]:
merged_df3 = pd.merge(df3,df4,on='id',how="outer")
merged_df3

    id     name       place
0    1      den         NaN
1    2     rome         NaN
2    3     luck         NaN
3    4  vignesh         NaN
4    5      peo         NaN
5    6   ganesh    Banglore
6    7      NaN         hyd
7    8      NaN  vijayawada
8    9      NaN     Lucknow
9   10      NaN      andhra
10  11      NaN          up

In [121]:
merged_df4 = pd.merge(df3,df4,on='id',how="outer")
merged_df4

    id     name       place
0    1      den         NaN
1    2     rome         NaN
2    3     luck         NaN
3    4  vignesh         NaN
4    5      peo         NaN
5    6   ganesh    Banglore
6    7      NaN         hyd
7    8      NaN  vijayawada
8    9      NaN     Lucknow
9   10      NaN      andhra
10  11      NaN          up

In [122]:
data3 = {"emp_id":[1,2,3,4,5,6],
        "name":["luck","bad","good","ganesh","parmesh","ramesh"],
        "dept":["HR","IT","IT","Finance","Finance","HR"]}

data4 = {"emp_id":[1,2,3,4,5,6],
        "dept":["HR","IT","Finance","Finance","HR","IT"],
         "Place":["Bangalore","hyd","lucknow","pune","mangalore","tirupati"]}

In [123]:
df5 = pd.DataFrame(data3)
df6 = pd.DataFrame(data4)

In [124]:
df5

   emp_id     name     dept
0       1     luck       HR
1       2      bad       IT
2       3     good       IT
3       4   ganesh  Finance
4       5  parmesh  Finance
5       6   ramesh       HR

In [125]:
df6

   emp_id     dept      Place
0       1       HR  Bangalore
1       2       IT        hyd
2       3  Finance    lucknow
3       4  Finance       pune
4       5       HR  mangalore
5       6       IT   tirupati

In [126]:
pd.merge(df5,df6,on=["emp_id","dept"],how="inner")

   emp_id    name     dept      Place
0       1    luck       HR  Bangalore
1       2     bad       IT        hyd
2       4  ganesh  Finance       pune

In [127]:
pd.merge(df5,df6,on=["emp_id","dept"],how="outer")

   emp_id     name     dept      Place
0       1     luck       HR  Bangalore
1       2      bad       IT        hyd
2       3      NaN  Finance    lucknow
3       3     good       IT        NaN
4       4   ganesh  Finance       pune
5       5  parmesh  Finance        NaN
6       5      NaN       HR  mangalore
7       6   ramesh       HR        NaN
8       6      NaN       IT   tirupati

In [128]:
pd.merge(df5,df6,on=["emp_id","dept"],how="left")

   emp_id     name     dept      Place
0       1     luck       HR  Bangalore
1       2      bad       IT        hyd
2       3     good       IT        NaN
3       4   ganesh  Finance       pune
4       5  parmesh  Finance        NaN
5       6   ramesh       HR        NaN

In [129]:
pd.merge(df5,df6,on=["emp_id","dept"],how="right")

   emp_id    name     dept      Place
0       1    luck       HR  Bangalore
1       2     bad       IT        hyd
2       3     NaN  Finance    lucknow
3       4  ganesh  Finance       pune
4       5     NaN       HR  mangalore
5       6     NaN       IT   tirupati

In [130]:
e1 = {"emp_id":[1,2,3,4,5,6],
      "name":["luck","bad","good","ganesh","parmesh","ramesh"]}
d1 = {"id":[1,2,3,4,5,6],
      "dept":["HR","IT","Finance","Finance","HR","IT"]}
e_df = pd.DataFrame(e1)
d_df = pd.DataFrame(d1)
d_df

   id     dept
0   1       HR
1   2       IT
2   3  Finance
3   4  Finance
4   5       HR
5   6       IT

In [131]:
e_df

   emp_id     name
0       1     luck
1       2      bad
2       3     good
3       4   ganesh
4       5  parmesh
5       6   ramesh

In [132]:
d_df

   id     dept
0   1       HR
1   2       IT
2   3  Finance
3   4  Finance
4   5       HR
5   6       IT

In [133]:
pd.merge(e_df,d_df,left_on="emp_id",right_on="id")

   emp_id     name  id     dept
0       1     luck   1       HR
1       2      bad   2       IT
2       3     good   3  Finance
3       4   ganesh   4  Finance
4       5  parmesh   5       HR
5       6   ramesh   6       IT